<?php
return [
    'id' => 'app-api',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'api\controllers',
    'bootstrap' => ['log'],
    'modules' => [
        'v1' => [
            'class' => 'api\modules\v1\Module',
        ],
    ],
    'components' => [
        'request' => [
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
            'enableCsrfValidation' => false,
            'enableCookieValidation' => false,
            'cookieValidationKey' => 'maktab-secret-api-cookie-key-2026-xyz',
        ],
        'response' => [
            'format' => yii\web\Response::FORMAT_JSON,
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableSession' => false,
            'loginUrl' => null,
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => [
                        'v1/student',
                        'v1/teacher',
                        'v1/school-class',
                        'v1/subject',
                        'v1/academic-year',
                        'v1/term',
                        'v1/room',
                        'v1/enrollment',
                        'v1/teacher-assignment',
                        'v1/calendar',
                        'v1/schedule',
                        'v1/lesson',
                        'v1/attendance',
                        'v1/grading-policy',
                        'v1/grade-category',
                        'v1/grade',
                        'v1/grade-override',
                        'v1/assignment',
                        'v1/submission',
                        'v1/question-bank',
                        'v1/question',
                        'v1/exam',
                        'v1/exam-attempt',
                        'v1/contract',
                        'v1/invoice',
                        'v1/payment',
                        'v1/coin-rule',
                        'v1/coin-transaction',
                        'v1/coin-reward',
                        'v1/achievement',
                        'v1/certificate',
                        'v1/announcement',
                        'v1/survey',
                        'v1/survey-response',
                        'v1/admission',
                    ],
                ],
                'POST v1/admission/apply' => 'v1/admission/apply',
                'PUT v1/admission/<id:\d+>/status' => 'v1/admission/update-status',
                'POST v1/admission/<id:\d+>/enroll' => 'v1/admission/enroll',
                'GET v1/admission/stats' => 'v1/admission/stats',
                'GET v1/cms/public' => 'v1/cms/public',
                'GET v1/cms/sections' => 'v1/cms/sections',
                'PUT v1/cms/sections/<id:\d+>' => 'v1/cms/update-section',
                'GET v1/cms/faqs' => 'v1/cms/faqs',
                'POST v1/cms/faqs' => 'v1/cms/create-faq',
                'PUT v1/cms/faqs/<id:\d+>' => 'v1/cms/update-faq',
                'GET v1/survey/<id:\d+>/detail' => 'v1/survey/detail',
                'POST v1/survey/<id:\d+>/submit' => 'v1/survey/submit',
                'GET v1/survey/<id:\d+>/analytics' => 'v1/survey/analytics',
                'POST v1/auth/login' => 'v1/auth/login',
                'POST v1/auth/register' => 'v1/auth/register',
                'GET v1/auth/profile' => 'v1/auth/profile',
                'POST v1/auth/change-password' => 'v1/auth/change-password',
                'POST v1/auth/logout' => 'v1/auth/logout',
                'POST v1/attendance/batch' => 'v1/attendance/batch',
                'GET v1/lesson/<id:\d+>/deadline' => 'v1/lesson/deadline',
                'POST v1/grade-override/<id:\d+>/approve' => 'v1/grade-override/approve',
                'POST v1/grade-override/<id:\d+>/reject' => 'v1/grade-override/reject',
                'POST v1/submission/<id:\d+>/grade' => 'v1/submission/grade',
                'POST v1/exam/<id:\d+>/start' => 'v1/exam/start',
                'POST v1/exam-attempt/<id:\d+>/submit' => 'v1/exam-attempt/submit',
                'POST v1/contract/<id:\d+>/generate-invoices' => 'v1/contract/generate-invoices',
                'POST v1/payment/pay' => 'v1/payment/pay',
                'POST v1/payment/<id:\d+>/reverse' => 'v1/payment/reverse',
                'POST v1/coin-transaction/award' => 'v1/coin-transaction/award',
                'POST v1/coin-transaction/spend' => 'v1/coin-transaction/spend',
                'GET v1/coin-transaction/balance/<student_id:\d+>' => 'v1/coin-transaction/balance',
                'GET v1/coin-transaction/leaderboard' => 'v1/coin-transaction/leaderboard',
                'POST v1/coin-reward/<id:\d+>/redeem' => 'v1/coin-reward/redeem',
                'GET v1/finance/stats' => 'v1/finance-stats/index',
                'POST v1/achievement/award' => 'v1/achievement/award',
                'POST v1/certificate/<id:\d+>/verify' => 'v1/certificate/verify',
                'GET v1/notification' => 'v1/notification/index',
                'POST v1/notification/<id:\d+>/read' => 'v1/notification/read',
                'GET v1/notification/unread-count' => 'v1/notification/unread-count',
                'GET v1/portal/student' => 'v1/portal/student',
                'GET v1/portal/parent' => 'v1/portal/parent',
                'GET v1/portal/teacher' => 'v1/portal/teacher',
                'GET v1/analytics/director' => 'v1/analytics/director',
                'GET v1/analytics/academic' => 'v1/analytics/academic',
                'GET v1/analytics/finance' => 'v1/analytics/finance',
                'GET v1/analytics/export' => 'v1/analytics/export',
                'GET v1/setting' => 'v1/setting/index',
                'PUT v1/setting' => 'v1/setting/update',
                'GET v1/audit-log' => 'v1/audit-log/index',
            ],
        ],
    ],
    'as corsFilter' => [
        'class' => \yii\filters\Cors::class,
    ],
];
